config/routes.rb
Rails.application.routes.draw do

  # Login pages
  devise_for :users

  #Concerns
  concern :group_result do
    resources :result_of_tests, only: [:index], path: 'results', param: :result_id
  end

  #Routes
  root 'static_pages#home'

  #Static pages
  # get 'about' => 'static_pages#about'
  # get 'contacts' => 'static_pages#contacts'
  get 'home' => 'static_pages#home'

  #Interests pages
  resources :interests, only: [:index, :destroy]
  resources :interests, only: [] do
    collection do
      #Adding create and update routes to index page
      post '' => 'interests#create'
      patch '' => 'interests#update'
    end
  end

  #User pages...
  #...Administrators
  resources :administrators, concerns: :group_result  do
    member do
      get 'delete' => 'administrators#delegate'
      delete 'delete' => 'administrators#delete'
    end
  end

  #...Mentors
  resources :mentors, concerns: :group_result do
    member do
      get 'delete' => 'mentors#delegate'
      delete 'delete' => 'mentors#delete'
    end
  end

  #...Clients
  resources :clients, concerns: :group_result do
    member do
      #Adding testing pages
      get 'tests' => 'testing_process#index', as: 'tests'
      get 'edit/update_mentors' => 'clients#update_mentors'
      get 'mode_settings' => 'clients#mode_settings'
      patch 'mode_settings' => 'clients#update_mode_settings'
    end
    resources :result_of_tests, except: [:new, :create, :index], path: 'results', param: :result_id
    get 'results/:result_id/heatmap'=> 'result_of_tests#show_heatmap', as: 'heatmap'
    get 'update_mentors' => 'clients#update_mentors', on: :new
  end

  scope '/testing_process' do
    get ':result_of_test_id/testing' => 'testing_process#testing', as: 'testing'
    post ':result_of_test_id/answer' => 'testing_process#answer', as: 'testing_answer'
    post 'clients/:id/tests/:test_id/start' => 'testing_process#begin', as: 'testing_begin'
    get ':result_of_test_id/finish' => 'testing_process#finish', as: 'finish_page'
  end

  #Tests pages
  resources :tests do
    get 'update_image' => 'tests#update_image', on: :new
    get 'questions/:question_number/get_image' => 'pictures#show'
    member do
      get 'summary_result', to: 'result_of_tests#summary_result'
      get 'edit/update_image' => 'tests#update_image'
    end
  end

  #Picture pages
  resources :pictures, except: [:show]

  # Translations
  resources :translations, only: %i[index update create] do
    collection do
      post :translated_columns, to: 'translations#create_translated_columns'
      patch 'translated_columns/:id', to: 'translations#update_translated_columns'
      post :create_language, to: 'translations#create_language'
    end
  end

  # Test availability
  resources :test_availabilities, only: %i[index] do
    collection do
      patch :batch_update, to: 'test_availabilities#batch_update'
    end
  end

  get 'summary_results', to: 'result_of_tests#summary_results'
  get 'summary_result_table', to: 'result_of_tests#summary_result_table'
end

app/models/translation.rb
# == Schema Information
#
# Table name: translations
#
#  id          :bigint           not null, primary key
#  field       :string           not null
#  value       :string           not null
#  language_id :bigint           not null
#

class Translation < ActiveRecord::Base
  belongs_to :language

  validates_presence_of :value, :field
end

app/controllers/translations_controller.rb
class TranslationsController < AdminController
  translations_for_preload %i[
    entities.translations.index
    common.menu.all
    common.menu.create
    common.menu.log_out
    common.menu.my_profile
    common.menu.profile
    common.menu.settings
    entities.clients.create
    entities.clients.index
    entities.interests.index
    entities.local_administrators.create
    entities.local_administrators.index
    entities.mentors.create
    entities.mentors.index
    entities.pictures.index
    entities.tests.index
    entities.translations.all_translations
  ]

  helper_method :active_tab?

  def index
    authorize!

    index_initialize
    @active_tab_id = params[:active_tab]
  end

  def update
    authorize!

    @translation = Translation.find(params[:id])

    if @translation.update(translation_params)
      flash[:success] = tf('common.flash.translation_updated')

      redirect_to translations_path(active_tab: @translation.language_id)
    else
      index_initialize
      @user = @translation
      @active_tab_id = @translation.language_id

      render :index
    end
  end

  def create
    authorize!

    @translation = Translation.new(translation_params)

    if @translation.save
      flash[:success] = tf('common.flash.translation_updated')

      redirect_to translations_path(active_tab: @translation.language_id)
    else
      index_initialize
      @user = @translation
      @active_tab_id = @translation.language_id

      render :index
    end
  end

  def create_language
    authorize!

    @language = Language.new(language_params)

    if @language.save
      flash[:success] = tf('common.flash.language_created')

      redirect_to translations_path
    else
      index_initialize
      @user = @language

      render :index
    end
  end

  def create_translated_columns
    authorize!

    @translation = TranslatedColumn.new(translated_column_params)

    if @translation.save
      flash[:success] = tf('common.flash.translation_updated')

      redirect_to translations_path(active_tab: @translation.language_id)
    else
      index_initialize
      @user = @translation
      @active_tab_id = @translation.language_id

      render :index
    end
  end

  def update_translated_columns
    authorize!

    @translation = Translation.find(params[:id])

    if @translation.update(translated_column_params)
      flash[:success] = tf('common.flash.translation_updated')

      redirect_to translations_path(active_tab: @translation.language_id)
    else
      index_initialize
      @user = @translation
      @active_tab_id = @translation.language_id

      render :index
    end
  end

  private

    def translated_column_params
      params
        .require(:translated_column)
        .permit(TranslatedColumn.attribute_names)
    end

    def translation_params
      params
        .require(:translation)
        .permit(Translation.attribute_names)
    end

    def language_params
      params
        .require(:language)
        .permit(:name)
    end

    def index_initialize
      @language ||= Language.new
      @translations_presenter = TranslationIndex.new
    end

    def active_tab?(id, index)
      @active_tab_id.to_s == id.to_s || @active_tab_id.blank? && index.zero?
    end
end

app/views/translations/_form.html.erb
<%
  url =
    if translation.id.present?
      translation_path(translation.id)
    else
      translations_path
    end
%>
<%= form_for translation.this, url: url do |f| %>
  <div class="row">
    <%= f.label "#{lang.name}.#{translation.field}",
                translation.value_en,
                class: 'col-sm-4 control-label'
    %>
    <div class="col-sm-6">
      <% if translation.text_area? %>
        <%= f.text_area :value,
                        class: 'form-control',
                        id: "#{lang.name}.#{translation.field}",
                        rows: 10
        %>
      <% else %>
          <%= f.text_field :value,
                           class: 'form-control',
                           id: "#{lang.name}.#{translation.field}"
          %>
      <% end %>
    </div>

    <%= f.hidden_field :id %>
    <%= f.hidden_field :language_id %>
    <%= f.hidden_field :field %>

    <%= f.submit tf('common.forms.edit'), class: 'col-sm-2 btn btn-warning' %>
  </div>
<% end %>

app/views/translations/_language_form.html.erb
<div class="row form-group">
  <%= form_for language, url: create_language_translations_path do |lang_form| %>
    <h4>
      <%= lang_form.label :name,
                          tf('entities.languages.create'),
                          class: 'col-sm-offset-5 col-sm-2 control-label'
      %>
    </h4>

    <div class="col-sm-4">
      <%= lang_form.text_field :name,
                               class: 'form-control',
                               placeholder: tf('entities.languages.fields.name')
      %>
    </div>

    <%= lang_form.submit tf('common.forms.add'),
                         class: 'col-sm-1 btn btn-primary'
    %>
  <% end %>
</div>

app/views/translations/_translated_columns_form.html.erb
<%
  url =
      if translation.id.present?
        translated_columns_translations_path(translation.id)
      else
        translated_columns_translations_path
      end
%>
<%= form_for translation.this, url: url do |f| %>
  <div class="row">
    <%= f.label "#{lang.name}.#{translation.field}",
                translation.value_en,
                class: 'col-sm-4 control-label'
    %>
    <div class="col-sm-6">
      <% if translation.text_area? %>
        <%= f.text_area :translation,
                        class: 'form-control',
                        id: "#{lang.name}.#{translation.field}",
                        rows: 10
        %>
      <% else %>
        <%= f.text_field :translation,
                         class: 'form-control',
                         id: "#{lang.name}.#{translation.field}"
        %>
      <% end %>
    </div>

    <%= f.hidden_field :id %>
    <%= f.hidden_field :translatable_type %>
    <%= f.hidden_field :language_id %>
    <%= f.hidden_field :translatable_id %>
    <%= f.hidden_field :target_column %>

    <%= f.submit tf('common.forms.edit'), class: 'col-sm-2 btn btn-warning' %>
  </div>
<% end %>

app/views/translations/index.html.erb
<% provide :title, tf('entities.translations.index') %>
<%= render 'shared/error_message' %>

<%= render partial: 'translations/language_form',
           locals: {
             language: @language
           }
%>

<h1><%= tf('entities.translations.all_translations') %></h1>

<div class="row col-sm-12">

  <!-- Lang tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <% @translations_presenter.languages.each.with_index do |lang, i| %>
      <%
        tab_class = active_tab?(lang.id, i) ? 'active' : ''
      %>
      <li role="presentation"
          class="<%= tab_class %>"
      >
        <a href="#<%= lang.name %>"
           aria-controls="<%= lang.name %>"
           role="tab"
           data-toggle="tab"
        >
          <%= lang.name %>
        </a>
      </li>
    <% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content row col-sm-offset-2 margin-top-20">
    <% @translations_presenter.grouped.each.with_index do |lang, i| %>
      <%
        tab_class = active_tab?(lang.id, i) ? 'active' : ''
      %>
      <div role="tabpanel"
           class="tab-pane col-sm-12 <%= tab_class %>"
           id="<%= lang.name %>"
      >
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation"
              class="active"
          >
            <a href="#<%= lang.name %>_literals"
               aria-controls="<%= lang.name %>_literals"
               role="tab"
               data-toggle="tab"
            >
              Website
            </a>
          </li>
          <li role="presentation"
              class=""
          >
            <a href="#<%= lang.name %>_content"
               aria-controls="<%= lang.name %>_content"
               role="tab"
               data-toggle="tab"
            >
              Content
            </a>
          </li>
        </ul>

        <div class="tab-content margin-top-20">

          <div role="tabpanel"
               class="tab-pane col-sm-12 active"
               id="<%= lang.name %>_literals"
          >
            <% lang.translations.each do |translation| %>
              <%= render partial: 'translations/form',
                         locals: { lang: lang, translation: translation }
              %>
            <% end %>
          </div>

          <div role="tabpanel"
               class="tab-pane col-sm-12"
               id="<%= lang.name %>_content"
          >
            <% lang.translated_columns.each do |translation| %>
              <%= render partial: 'translations/translated_columns_form',
                         locals: { lang: lang, translation: translation }
              %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>