config/routes.rb
Rails.application.routes.draw do

  # Login pages
  devise_for :users

  #Concerns
  concern :group_result do
    resources :result_of_tests, only: [:index], path: 'results', param: :result_id
  end

  #Routes
  root 'static_pages#home'

  #Static pages
  # get 'about' => 'static_pages#about'
  # get 'contacts' => 'static_pages#contacts'
  get 'home' => 'static_pages#home'

  #Interests pages
  resources :interests, only: [:index, :destroy]
  resources :interests, only: [] do
    collection do
      #Adding create and update routes to index page
      post '' => 'interests#create'
      patch '' => 'interests#update'
    end
  end

  #User pages...
  #...Administrators
  resources :administrators, concerns: :group_result  do
    member do
      get 'delete' => 'administrators#delegate'
      delete 'delete' => 'administrators#delete'
    end
  end

  #...Mentors
  resources :mentors, concerns: :group_result do
    member do
      get 'delete' => 'mentors#delegate'
      delete 'delete' => 'mentors#delete'
    end
  end

  #...Clients
  resources :clients, concerns: :group_result do
    member do
      #Adding testing pages
      get 'tests' => 'testing_process#index', as: 'tests'
      get 'edit/update_mentors' => 'clients#update_mentors'
      get 'mode_settings' => 'clients#mode_settings'
      patch 'mode_settings' => 'clients#update_mode_settings'
    end
    resources :result_of_tests, except: [:new, :create, :index], path: 'results', param: :result_id
    get 'results/:result_id/heatmap'=> 'result_of_tests#show_heatmap', as: 'heatmap'
    get 'update_mentors' => 'clients#update_mentors', on: :new
  end

  scope '/testing_process' do
    get ':result_of_test_id/testing' => 'testing_process#testing', as: 'testing'
    post ':result_of_test_id/answer' => 'testing_process#answer', as: 'testing_answer'
    post 'clients/:id/tests/:test_id/start' => 'testing_process#begin', as: 'testing_begin'
    get ':result_of_test_id/finish' => 'testing_process#finish', as: 'finish_page'
  end

  #Tests pages
  resources :tests do
    get 'update_image' => 'tests#update_image', on: :new
    get 'questions/:question_number/get_image' => 'pictures#show'
    member do
      get 'summary_result', to: 'result_of_tests#summary_result'
      get 'edit/update_image' => 'tests#update_image'
    end
  end

  #Picture pages
  resources :pictures, except: [:show]

  # Translations
  resources :translations, only: %i[index update create] do
    collection do
      post :translated_columns, to: 'translations#create_translated_columns'
      patch 'translated_columns/:id', to: 'translations#update_translated_columns'
      post :create_language, to: 'translations#create_language'
    end
  end

  # Test availability
  resources :test_availabilities, only: %i[index] do
    collection do
      patch :batch_update, to: 'test_availabilities#batch_update'
    end
  end

  get 'summary_results', to: 'result_of_tests#summary_results'
  get 'summary_result_table', to: 'result_of_tests#summary_result_table'
end

app/models/result_of_test.rb
# == Schema Information
#
# Table name: result_of_tests
#
#  id                  :integer          not null, primary key
#  emotion_recognition :boolean          default(FALSE)
#  gaze_trace          :boolean          default(FALSE)
#  is_ended            :boolean
#  is_outdated         :boolean          default(FALSE)
#  was_in_school       :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  client_id           :integer
#  test_id             :integer
#

class ResultOfTest < ActiveRecord::Base
  include TranslatableModels

  before_validation :setup_fields, on: :create

  belongs_to :test
  belongs_to :client

  has_many :question_results, dependent: :destroy

  accepts_nested_attributes_for :question_results

  scope :result_page, -> { includes(:question_results, question_results: [:question, question: [:picture]]) }

  validates :test, :client, presence: true
  validates :was_in_school, exclusion: { in: [nil] }

  #Setups default fields
  def setup_fields
    self.is_ended = false
    self.is_outdated = false
    true
  end

  #Returns the question after last answered
  def last_question
    questions = QuestionResult.order(:number).where(result_of_test_id: self.id)
    Question.where(test_id: self.test_id, number: (questions.count == 0) ? 1 : questions.count + 1).first
  end

  def get_question(number)
    get_question_result(number).question
  end

  def get_question_result(number)
    QuestionResult.includes(:question).where(result_of_test_id: self.id, number: number).first
  end

  #Returns last answered question
  def previous_question
    QuestionResult.order(:number).where(result_of_test_id: self.id).last&.question
    # previous_number = (questions.count <= 1) ? 1 : questions.count - 1
    # Question.where(test_id: self.test_id, number: previous_number).first
  end

  def show_short
    result_info = {date_of_start: self.created_at}  
    result_info[:name_of_test] = Test.find(self.test_id).name
    result_info[:id] = self.id
    result_info[:client_id] = self.client_id
    result_info[:user_id] = client.user.id
    result_info[:is_ended] = self.is_ended
    result_info[:test_id] = self.test_id
    result_info[:date_of_end] = ''
    if is_ended?
      result_info[:date_of_end] = QuestionResult.order(:created_at).where(result_of_test_id: self.id).last.created_at
    end
    result_info[:is_outdated] = self.is_outdated
    result_info
  end

  def show_time_to_answer
    timeline = {}
    results = QuestionResult.order(:number).where(result_of_test_id: self.id)
    results.each do |r|
      timeline[r.number] = r.end - r.start
    end
    timeline
  end

  def show_timeline
    timeline = []
    duration = 0
    results = QuestionResult.order(:number).where(result_of_test_id: self.id)
    states = [
      tf('entities.result_of_tests.was_checked.thumbs_down'),
      tf('entities.result_of_tests.was_checked.question_mark'),
      tf('entities.result_of_tests.was_checked.thumbs_up')
    ]
    results.each do |r|
      human_was_checked = states[r.was_checked - 1]
      timeline << [human_was_checked, duration, duration + (r.end - r.start)]
      duration += r.end - r.start
    end
    timeline
  end

  def show_emotion_dynamic
    list = {}
    r = Random.new
    question_results.map(&:get_emotion_lists).each_with_index do |question_emotions, i|
      list.merge!(question_emotions.transform_values { |emo_arr| emo_arr.map { |emo_v| [r.rand(i.to_f), emo_v] } }) do |_, a, b|
        a + b
      end
    end
    list
  end

  def show_plausible_emotion_states_dynamic
    list = {}
    r = Random.new
    question_results.map(&:get_plausible_emotion_states).each_with_index do |question_emotions, i|
      step = 1.0 / question_emotions.count
      question_emotions.each_with_index do |q_e, j|
        list.merge!({q_e.first => [[i + 1 + step * j, q_e.second.to_f]]}) do |_, a, b|
        # list.merge!({q_e.first => [[r.rand(i.to_f), q_e.second.to_f]]}) do |_, a, b|
          a + b
        end
      end
    end
    list
  end

  def average_inside_picture
    gaze_results = question_results.includes(:gaze_trace_result).map do |qr|
      qr.gaze_trace_result
    end
    sum = gaze_results
              .select { |gr| gr.gaze_points.present? }
              .map { |gr| gr.inside_picture_points.count / gr.gaze_points.count.to_f }
              .reduce(&:+)
    total = gaze_results.count.to_f
    sum / total
  end

  def average_inside_buttons
    gaze_results = question_results.includes(:gaze_trace_result).map do |qr|
      qr.gaze_trace_result
    end
    sum = gaze_results
              .select { |gr| gr.gaze_points.present? }
              .map { |gr| gr.inside_buttons_points.count / gr.gaze_points.count.to_f }
              .reduce(&:+)
    total = gaze_results.count.to_f
    sum / total
  end

  def without_gazes
    gaze_results = question_results.includes(:gaze_trace_result).map do |qr|
      qr.gaze_trace_result
    end
    gaze_results.select { |gr| gr.gaze_points.blank? }.count
  end

  def without_emotions
    emotion_states = question_results.includes(:emotion_state_result).map(&:emotion_state_result)
    emotion_states.select { |es| es&.states.blank? }.count
  end

  def correlates_with_positive
    EmotionMultiplierCalculator.new(question_results).correlates_with_positive_emotion.count / question_results.count.to_f
  end

  def correlates_with_negative
    EmotionMultiplierCalculator.new(question_results).correlates_with_negative_emotion.count / question_results.count.to_f
  end

  def count_neutral
    EmotionMultiplierCalculator.new(question_results).neutral_states.count / question_results.count.to_f
  end

  def clear_dups_es
    all_esr = question_results.map(&:emotion_state_result)
    checked_states = []
    all_esr.each do |esr|
      emotion_states = esr.states.values
      values_to_save = emotion_states.select { |emotion_state| checked_states.find_index(emotion_state).blank? }
      checked_states += values_to_save
      esr.states = values_to_save.map.with_index { |v, i| [i, v] }.to_h
    end
  end

  def progress
    answered_count = question_results.count
    total = test.questions.count
    [answered_count, total]
  end

  private :setup_fields
end

app/controllers/result_of_tests_controller.rb
class ResultOfTestsController < AdminController
  translations_for_preload %i[
    common.flash.test_unfinished
    common.flash.update_complete
    common.flash.test_result_outdated
    common.flash.test_result_deleted
    common.flash.cant_find_client
    common.flash.cant_find_test
    common.flash.empty_test
  ]

  def edit
    @result = ResultOfTest.find_by(id: params[:result_id])
    authorize!(@result)
    @user = @result
    #Only finished results are editable
    unless @result.is_ended
	    flash[:warning] = tf('common.flash.test_unfinished')
      redirect_back fallback_location: client_path(params[:client_id])
    end
  end

  def update
    @result = ResultOfTest.find_by(id: params[:result_id])
    authorize!(@result)
    @user = @result
    if @result.update(result_params)
      flash[:success] = tf('common.flash.update_complete')
      redirect_to(client_result_of_test_path(params[:client_id], params[:result_id]))
    else
      render :edit
    end
  end

  def show
    result = ResultOfTest.result_page.find_by(id: params[:result_id])
    @result = result
    @test = Test.select(:id, :name).find(result.test_id)
    result.language_id = current_user.language_id

    authorize!(result)

    #If test was changed, results are outdated
    if result.is_outdated?
      flash.now[:danger] = tf('common.flash.test_result_outdated')
    end

    avg_time_per_interest = {}
    #Loading question results
    q_res  = result.question_results.order(:number)
    q_test = Question.where(test_id: result.test_id) #questions of test
    #Loading all interests
    interests = {}
    interests_max = {}
    timestamps = []
    #Making array of interests
    q_res.each do |r|
      timestamps << r.show
      #Related interests for result
      related_i = {}
      q_test.each do |q|
        attachment =
            if q.youtube?
              q.youtube_link
            else
              q.picture
            end
        wrap_language(attachment)
        related_i = attachment.related_interests if q.number == r.number
      end
      related_i.each_key do |interest|
        if interests[interest].nil?
          interests_max[interest] = related_i[interest]
          interests[interest] = 0
          avg_time_per_interest[interest] = r.end - r.start
          interests[interest] = related_i[interest] if r.was_checked == 3 #Was thumbs up
        else
          interests_max[interest] += related_i[interest]
          interests[interest] += related_i[interest] if r.was_checked == 3
          avg_time_per_interest[interest] += r.end - r.start
        end
      end
    end
    avg_time_per_interest.each_key do |k|
      avg_time_per_interest[k] /= interests.count
    end
    client = Client.find(result.client_id)
    @client_user = client.user
    #Sorting
    @list_interests = interests.to_a.sort{ |x,y| y[1] - x[1]}
    @list_timestamps = timestamps
    @list_interests_max = interests_max
    @client = client.code_name.titleize
    @res = [
      result.was_in_school,
      result.show_time_to_answer,
      avg_time_per_interest,
      result.show_timeline,
      result.show_emotion_dynamic
    ]
    @has_heatmap = result.gaze_trace?
    if @has_heatmap
      gaze_calculator = GazeMultiplierCalculator.new(q_res)
      @list_interests_with_gaze = gaze_calculator.recount_results(@list_interests.to_h, @list_interests_max)
    end

    @has_emotion_track = result.emotion_recognition?

    if @has_emotion_track
      emotion_calculator = EmotionMultiplierCalculator.new(q_res)
      @list_interests_with_emotions = emotion_calculator.recount_results(@list_interests.to_h, @list_interests_max)
    end

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"result of #{@client}.xlsx\""
      }
    end
  end

  def index
    user = User.find_by(id: params[:client_id])
    authorize!(user)

    client = user.client
    results = ResultOfTest.where(client_id: client.id).order(:created_at).reverse_order
    @code_name = client.code_name
    @results = []
    results.each do |result|
      @results << result.show_short
    end
    @results = Kaminari.paginate_array(@results).page(params[:page]).per(5)
    #Preparing graphs
    @interest_points = client.get_client_interests[:points_interests]
    @avg_time = client.get_client_interests[:avg_answer_time]
  end

  def destroy
    result = ResultOfTest.find_by(id: params[:result_id])
    authorize!(result)

    if result.destroy
      flash[:success] = tf('common.flash.test_result_deleted')
    else
      flash[:error] = tf('entities.result_of_tests.errors.delete')
    end

    redirect_back fallback_location: client_path(params[:client_id])
  end

  def show_heatmap
    @result = ResultOfTest.result_page.find_by(id: params[:result_id])
    authorize!(@result)
    @test = @result.test

    #Loading client
    @client = @result.client

    if @test.blank? || @client.blank?
      #Cant find test or client
      flash[:danger] = tf('common.flash.cant_find_client') if @client.blank?
      flash[:danger] = tf('common.flash.cant_find_test') if @test.blank?
      redirect_back fallback_location: show_path_resolver(current_user) and return
    end

    #Checking questions in test
    if @test.questions.blank?
      flash[:danger] = tf('common.flash.empty_test')
      redirect_back fallback_location: show_path_resolver(current_user) and return
    end

    #Filling first question
    question_result = @result.get_question_result(params[:number] || 1)
    @question = question_result.question
    @description = @question.picture.description
    @image = @question.picture.image
    @heatmap = question_result.gaze_trace_result
  end

  def summary_results
    authorize!

    @tree = UsersTreeLoader.new(current_user, nil)
    @results_tree = @tree.call(params: params[:q])
  end

  def summary_result
    @test = Test.find(params[:id])

    @summary_target =
      if params[:user_id].present?
        User.find(params[:user_id])
      else
        current_user
      end

    authorize!(@summary_target, with: ResultOfTestPolicy)

    @name =
      if @summary_target.client?
        @summary_target.client.code_name
      else
        @summary_target.employee.full_name
      end

    user_tree = UsersTreeLoader.new(@summary_target, @test.id)
    user_tree.call
    @calc = SummaryResultCalculator.new(user_tree.results, current_user.language_id)


    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"Test #{@test.name} summary result.xlsx\""
      }
    end
  end

  def summary_result_table

    @summary_target =
      if params[:user_id].present?
        User.find(params[:user_id])
      else
        current_user
      end

    authorize!(@summary_target, with: ResultOfTestPolicy)

    @name =
      if @summary_target.client?
        @summary_target.client.code_name
      else
        @summary_target.employee.full_name
      end

    user_tree = UsersTreeLoader.new(@summary_target, nil)
    user_tree.call
    @calc = SummaryTableCalculator.new(user_tree.results, current_user.language_id)


    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"Tests summary table result.xlsx\""
      }
    end
  end

  private
    def result_params
      params
        .require(:result_of_test)
        .permit(question_results_attributes: %i[was_checked id])
    end
end

app/views/result_of_tests/edit.html.erb
<% provide(:title, tf('entities.result_of_tests.update')) %>

<%= render 'shared/error_message' %>

<h1 class="row col-sm-offset-4"><%= tf('entities.result_of_tests.update') %></h1>

<%= form_for @result,
             class: "form-horizontal",
             url: client_result_of_test_path(params[:client_id], params[:result_id]) do |result_form|
%>
	<%= result_form.fields_for :question_results do |question_form| %>
		<div class="row col-sm-offset-2">
			<h4 class="col-sm-4">
        <%= tf('entities.result_of_tests.fields.question_number') %>#<%= question_form.object.number %>
      </h4>
		</div>

		<div class="row col-sm-offset-2">
			<h4 class="col-sm-4">
        <%= tf('entities.result_of_tests.fields.time') %>: <%= question_form.object.total_time %>
      </h4>
		</div>

		<div class="row col-sm-offset-2 form-group">
			<%= question_form.label :was_checked,
                              tf('entities.result_of_tests.fields.answer'),
                              class: 'col-sm-2 control-label'
      %>
			<div class="col-sm-4">
				<%= question_form.select :was_checked,
                                 options_for_select([
                                   [tf('entities.result_of_tests.was_checked.thumbs_down'), 1],
                                   [tf('entities.result_of_tests.was_checked.question_mark'), 2],
                                   [tf('entities.result_of_tests.was_checked.thumbs_up'), 3]
                                 ], question_form.object.was_checked),
                                 {},
                                 { class: 'form-control' }
				 %>
			 </div>
		</div>
	<% end %>
	
	<div class="row col-sm-offset-2 form-group">
		<div class="col-sm-offset-2 col-sm-2">
			<%= result_form.submit tf('common.forms.confirm'), class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/result_of_tests/show.html.erb
<% provide(:title, tf('entities.result_of_tests.result')) %>
<%= javascript_include_tag 'charts_events' %>
<%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>

<div class= "row">
	<h2>
    <%= tf('entities.result_of_tests.results_of') %> <%= link_to @client, client_path(@client_user) %>, <%= @test.name %>
  </h2>
</div>

<div class= "row">
  <h3><%= tf('entities.result_of_tests.attending_at_the_moment') %>: <%= tf("common.boolean.#{@res[0]}") %></h3>
</div>

<!-- Add designed btn -->
<div class="row">
  <%= link_to client_result_of_test_path(params[:client_id], params[:result_id], format: :xlsx),
              data: { turbolinks: false },
              class: 'btn btn-success' do
  %>
    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>&#8194;<%= tf('entities.result_of_tests.download_as') %> xlsx
  <% end %>
  <% if !@result.is_outdated? && @result.is_ended? %>
    <%= link_to finish_page_path(params[:result_id]),
                class: 'btn btn-default' do
    %>
      <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&#8194;<%= tf('testing_process.finish_page') %>
    <% end %>
<% end %>

  <% if @has_heatmap %>
    <%= link_to tf('entities.result_of_tests.heatmap'),
                client_heatmap_path(params[:client_id], params[:result_id]),
                class: 'btn btn-success'
    %>
  <% end %>

</div>

<div class="row">
  <!-- Table Questions -->
	<div class="col-sm-6 row">
		  <table class="table table-hover">
      <thead>
      <h1><%= tf('entities.questions.index') %></h1>
        <tr>
          <td><h4>#</h4></td>
          <td><h4><%= tf('entities.result_of_tests.fields.start_date') %></h4></td>
          <td><h4><%= tf('entities.result_of_tests.fields.end_date') %></h4></td>
          <td><h4><%= tf('entities.result_of_tests.fields.time') %></h4></td>
          <td><h4><%= tf('entities.result_of_tests.fields.was_rewrited') %></h4></td>
          <td><h4><%= tf('entities.result_of_tests.fields.answer') %></h4></td>
        </tr>
      </thead>
			<% @list_timestamps.each_with_index do |element, i|%>
          <% if element[:question_id].blank? %>
              <tr class="danger" title="<%= tf('entities.result_of_tests.question_deleted') %>">
          <% else %>
              <tr>
          <% end %>
					<td class="col-sm-1"><h4><%= i + 1 %></h4></td>
					<td class="col-sm-3"><h4><small><%= date_to_local(element[:start]) %></small></h4></td>
					<td class="col-sm-3"><h4><small><%= date_to_local(element[:end]) %></small></h4></td>
					<td class="col-sm-2"><h4><small><%= '%0.2f s'%[element[:end] - element[:start]] %></small></h4></td>
					<td class="col-sm-1"><h4><small><%= tf("common.boolean.#{element[:was_rewrited]}") %></small></h4></td>
					<td class="col-sm-3">
            <h4>
              <small>
                <% if element[:was_checked] == 3 %>
                  <div><%= tf('entities.result_of_tests.was_checked.thumbs_up') %></div>
                <% elsif element[:was_checked] == 1 %>
                  <div><%= tf('entities.result_of_tests.was_checked.thumbs_down') %></div>
                <% else %>
                  <div><%= tf('entities.result_of_tests.was_checked.question_mark') %></div>
                <% end %>
						  </small>
            </h4>
          </td>
				</tr>
			<% end %>
		</table>
	</div>

  <!-- Interests points -->
  <div class="col-sm-offset-1 col-sm-5">
    <table class="table table-hover">
      <thead>
      <h1><%= tf('entities.result_of_tests.earned_points') %></h1>
      <tr>
        <td><h4><%= tf('entities.interests.interest') %></h4></td>
        <td><h4><%= tf('entities.result_of_tests.summary') %></h4></td>
        <% if @has_heatmap %>
          <td><h4>With gaze analysis</h4></td>
        <% end %>
        <% if @has_emotion_track %>
          <td><h4>With emotion analysis</h4></td>
        <% end %>
      </tr>
      </thead>
      <% @list_interests.each do |element|%>
          <tr>
            <td><h4><small><%= element[0].to_s.humanize %></small></h4></td>
            <td><h4><small><%= element[1] %>/<%= @list_interests_max[element[0]] %></small></h4></td>
            <% if @has_heatmap %>
              <td>
                <h4>
                  <small>
                    <%= @list_interests_with_gaze[element[0]].round(2) %>/<%= @list_interests_max[element[0]] %>
                  </small>
                </h4>
              </td>
            <% end %>
            <% if @has_emotion_track %>
              <td>
                <h4>
                  <small>
                    <%= @list_interests_with_emotions[element[0]].round(2) %>/<%= @list_interests_max[element[0]] %>
                  </small>
                </h4>
              </td>
            <% end %>
          </tr>
      <% end %>
    </table>
  </div>
</div>

<!-- Edit btn -->
<div class="row col-sm-4" style="margin-bottom: 15px;">
  <% unless @i_am_client %>
      <%= link_to tf('entities.result_of_tests.update'),
                  edit_client_result_of_test_path(params[:client_id],params[:result_id]),
                  class: "btn btn-warning"
      %>
  <% else %>
      <h4><%= tf('entities.result_of_tests.edit_request') %></h4>
  <% end %>
</div>

<!-- Graphs -->
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#answer_time" data-toggle="tab">
          <%= tf('entities.result_of_tests.time_of_answer') %>
        </a>
      </li>
      <li>
        <a href="#interests_points" data-toggle="tab">
          <%= tf('entities.result_of_tests.interest_points') %>
        </a>
      </li>
      <li>
        <a href="#avg_interests" data-toggle="tab">
          <%= tf('entities.result_of_tests.average_answer') %>
        </a>
      </li>
      <li>
        <a href="#timeline" data-toggle="tab">
          <%= tf('entities.result_of_tests.timeline') %>
        </a>
      </li>
      <% if @has_emotion_track %>
        <li>
          <a href="#emotion_dynamic" data-toggle="tab">Emotion dynamic</a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade in active" id="answer_time">
        <%= column_chart @res[1],
                         id: 'answer_time_chart',
                         xtitle: tf('entities.result_of_tests.fields.question_number'),
                         ytitle: tf('entities.result_of_tests.time_of_answer_short'),
                         download: true
        %>
      </div>
      <div class="tab-pane fade" id="avg_interests">
        <%= column_chart @res[2],
                         id: 'avg_interests_chart',
                         xtitle: tf('entities.interests.interest'),
                         ytitle: tf('entities.result_of_tests.average_answer_short'),
                         download: true,
                         discrete: true
        %>
      </div>
      <div class="tab-pane fade" id="interests_points">
        <%= pie_chart @list_interests,
                      download: true
        %>
      </div>
      <div class="tab-pane fade" id="timeline">
        <%= timeline @res[3],
                     id: 'timeline_chart',
                     download: true
        %>
      </div>
      <% if @has_emotion_track %>
        <div class="tab-pane fade" id="emotion_dynamic">
          <%= scatter_chart @res[4].map { |k, v| { name: k, data: v } },
                            id: 'emotion_dynamic_chart',
                            xtitle: tf('entities.result_of_tests.fields.question_number'),
                            ytitle: 'Emotion score',
                            download: true,
                            library: {
                                scales: {
                                    xAxes: [{
                                        ticks: {
                                            min: 1,
                                            max: @list_timestamps.count,
                                            stepSize: 1
                                        }
                                    }]
                                }
                            }
          %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="modal-info"
     data-test_id="<%= @test.id %>"
></div>
<%= render partial: 'result_of_tests/show/modal_picture' %>

<!--Fix of bug with not showing titles of OX-->
<script>
    $('a[href="#avg_interests"]').on('shown.bs.tab', function() {
        var chart = Chartkick.charts['avg_interests_chart'];
        chart.redraw();
    });
    $('a[href="#timeline"]').on('shown.bs.tab', function() {
        var chart = Chartkick.charts['timeline_chart'];
        chart.redraw();
    });
</script>

app/views/result_of_tests/summary_result.html.erb
<% provide(:title, "Test #{@test.name} summary result") %>
<%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>

<div class= "row">
  <h2>
    <% if @summary_target.client? %>
      <%= tf('entities.result_of_tests.results_of') %>
    <% else %>
      <%= tf('entities.result_of_tests.group_summary') %>
    <% end %>
    <%= link_to @name, show_path_resolver(@summary_target) %>
  </h2>
</div>

<!-- Add designed btn -->
<div class="row">
  <%= link_to summary_result_test_path(@test.id, user_id: @summary_target.id, format: :xlsx),
              data: { turbolinks: false },
              class: 'btn btn-success' do
  %>
    <span class="glyphicon glyphicon-download-alt"
          aria-hidden="true"
    ></span>
    &#8194;
    <%= tf('entities.result_of_tests.download_as') %> xlsx
  <% end %>

</div>

<div class="row">
  <!-- Table Questions -->
  <div class="col-sm-6 row">
    <%= render partial: 'result_of_tests/summary_result/table_answer_time',
               locals: {
                 answer_timestamps: @calc.table_answer_time
               }
    %>
  </div>

  <!-- Interests points -->
  <div class="col-sm-offset-1 col-sm-5">
    <%= render partial: 'result_of_tests/summary_result/table_interest_points',
               locals: {
                 interest_points: @calc.table_interest_points
               }
    %>
  </div>
</div>

<!-- Graphs -->
<div class="row">
  <div class="col-sm-12">
    <%= render partial: 'result_of_tests/summary_result/graphs',
               locals: {
                 answer_time: @calc.to_graph_data(@calc.table_answer_time, :number, :answer_time),
                 avg_interests: @calc.to_graph_data(@calc.avg_answer_time_by_interest, :name, :avg_time),
                 interests_points: @calc.to_graph_data(@calc.table_interest_points, :name, :total_weight)
               }
    %>
  </div>
</div>