config/routes.rb
Rails.application.routes.draw do

  # Login pages
  devise_for :users

  #Concerns
  concern :group_result do
    resources :result_of_tests, only: [:index], path: 'results', param: :result_id
  end

  #Routes
  root 'static_pages#home'

  #Static pages
  # get 'about' => 'static_pages#about'
  # get 'contacts' => 'static_pages#contacts'
  get 'home' => 'static_pages#home'

  #Interests pages
  resources :interests, only: [:index, :destroy]
  resources :interests, only: [] do
    collection do
      #Adding create and update routes to index page
      post '' => 'interests#create'
      patch '' => 'interests#update'
    end
  end

  #User pages...
  #...Administrators
  resources :administrators, concerns: :group_result  do
    member do
      get 'delete' => 'administrators#delegate'
      delete 'delete' => 'administrators#delete'
    end
  end

  #...Mentors
  resources :mentors, concerns: :group_result do
    member do
      get 'delete' => 'mentors#delegate'
      delete 'delete' => 'mentors#delete'
    end
  end

  #...Clients
  resources :clients, concerns: :group_result do
    member do
      #Adding testing pages
      get 'tests' => 'testing_process#index', as: 'tests'
      get 'edit/update_mentors' => 'clients#update_mentors'
      get 'mode_settings' => 'clients#mode_settings'
      patch 'mode_settings' => 'clients#update_mode_settings'
    end
    resources :result_of_tests, except: [:new, :create, :index], path: 'results', param: :result_id
    get 'results/:result_id/heatmap'=> 'result_of_tests#show_heatmap', as: 'heatmap'
    get 'update_mentors' => 'clients#update_mentors', on: :new
  end

  scope '/testing_process' do
    get ':result_of_test_id/testing' => 'testing_process#testing', as: 'testing'
    post ':result_of_test_id/answer' => 'testing_process#answer', as: 'testing_answer'
    post 'clients/:id/tests/:test_id/start' => 'testing_process#begin', as: 'testing_begin'
    get ':result_of_test_id/finish' => 'testing_process#finish', as: 'finish_page'
  end

  #Tests pages
  resources :tests do
    get 'update_image' => 'tests#update_image', on: :new
    get 'questions/:question_number/get_image' => 'pictures#show'
    member do
      get 'summary_result', to: 'result_of_tests#summary_result'
      get 'edit/update_image' => 'tests#update_image'
    end
  end

  #Picture pages
  resources :pictures, except: [:show]

  # Translations
  resources :translations, only: %i[index update create] do
    collection do
      post :translated_columns, to: 'translations#create_translated_columns'
      patch 'translated_columns/:id', to: 'translations#update_translated_columns'
      post :create_language, to: 'translations#create_language'
    end
  end

  # Test availability
  resources :test_availabilities, only: %i[index] do
    collection do
      patch :batch_update, to: 'test_availabilities#batch_update'
    end
  end

  get 'summary_results', to: 'result_of_tests#summary_results'
  get 'summary_result_table', to: 'result_of_tests#summary_result_table'
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id          :integer          not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Picture < ActiveRecord::Base
  include TranslatableModels
  include Translatable

  MAX_ATTACHMENT_SIZE = 1.megabyte.freeze

  define_translatable_columns %i[description]

  has_many :picture_interests, inverse_of: :picture, dependent: :destroy
  has_many :interests, :through => :picture_interests
  has_many :questions, dependent: :destroy

  has_one_attached :image
  has_one_attached :audio
  accepts_nested_attributes_for :picture_interests, reject_if: :all_blank, allow_destroy: true

  validates :description, presence: true, length: {in: 5..50}
  validates :picture_interests, nested_attributes_uniqueness: {field: :interest_id}
  validate :image_validation

  #returns related interests to a picture
  def related_interests
    links = PictureInterest.where(picture_id: self.id)
    result = {}
    links.each do |link|
      interest = Translatable.wrap_language(Interest.find(link.interest_id), language_id)
      result[interest.name] = link.earned_points
    end
    result
  end

  def small_variant
    opts =
        if gif?
          { coalesce: true, quality: 40, resize: '150x150' }
        else
          { quality: 40, resize: '150x150' }
        end
    image.variant(opts)
  end

  def middle_variant
    # was 80%, 300x300 - too blurry
    opts =
        if gif?
          { coalesce: true, quality: 90, resize: '550x550' }
        else
          { quality: 90, resize: '550x550' }
        end
    image.variant(opts)
  end

  #Returns all pictures
  def self.pictures_list
    Picture.with_attached_image.order(:description).map do |t|
      ["%{name}"%{name: t.description}, t.id]
    end
  end

  def gif?
    image.blob.content_type.starts_with?('image/gif')
  end

  def image?
    !gif?
  end

  private
    def image_validation
      return unless image.attached?

      unless image.blob.content_type.starts_with?('image/')
        image.purge
        errors.add(:image, :attachment_invalid)
        return
      end

      if image.blob.byte_size > MAX_ATTACHMENT_SIZE
        image.purge
        errors.add(:image, :attachment_too_big)
      end
    end
end

app/controllers/pictures_controller.rb
class PicturesController < AdminController
  translations_for_preload %i[
    common.flash.picture_created
    common.flash.picture_deleted
    common.flash.picture_updated
    common.forms.confirm
    entities.interests.interest
    entities.pictures.add_interest
    entities.pictures.fields.description
    entities.pictures.fields.image
    entities.pictures.fields.weight
    entities.pictures.remove_interest
  ]

  def index
    authorize!
    picture_query = Picture.with_attached_image.includes(:picture_interests).order(:created_at).reverse_order
    @q = picture_query.ransack(params[:q])
    @pictures = params[:q] && params[:q][:s] ? @q.result.order(params[:q][:s]) : @q.result
    @pictures = @pictures.page(params[:page]).per(5)
  end

  def new
    authorize!
    @picture = Picture.new
    @interests = Interest.interests_list
  end

  def create
    authorize!
    @picture = Picture.new(picture_params)

    respond_to do |types|
      types.json do
        if @picture.save
          flash[:success] = tf('common.flash.picture_created')

          render json: {
            response: {
              type: :success,
              message: tf('common.flash.picture_created')
            }
          }, status: :ok
        else

          render json: {
              response: {
                  type: :error,
                  fields: @picture.errors.messages,
                  full_messages: translate_errors(@picture.errors, @picture)
              }
          }, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @picture = Picture.find(params[:id])
    authorize!(@picture)
    @interests = Interest.interests_list
  end

  def update
    @picture = Picture.find(params[:id])
    authorize!(@picture)

    respond_to do |types|
      types.json do
        if @picture.update(picture_params)
          flash[:success] = tf('common.flash.picture_updated')
          render json: { response: { type: :success } }, status: :ok
        else
          render json: {
              response: {
                  type: :error,
                  errors: @picture.errors.messages,
                  full_messages: translate_errors(@picture.errors, @picture)
              }
          }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    authorize!(picture)
    if picture.destroy
      flash[:success] = tf('common.flash.picture_deleted')
    else
      @user = picture
    end
    index
    render :index
  end

  def show
    question = Question.find_by(number: params[:question_number], test_id: params[:test_id])
    authorize!

    if question.blank?
      render json: {}, status: :not_found
      return
    end

    attachment = question.attachment
    if question.youtube?
      link = attachment.embed
      type = 'youtube'
      edit_link = ''
    else
      link = url_for(attachment.middle_variant)
      type = 'picture'
      edit_link = edit_picture_path(attachment.id)
    end

    respond_to do |types|
      types.json do
        render json: {
          title: '',
          link: link,
          type: type,
          edit_link: edit_link
        }
      end
    end
  end

  private

    def picture_params
      params
        .require(:picture)
        .permit(
          :description,
          :image,
          :audio,
          picture_interests_attributes: [
            :interest_id,
            :earned_points,
            :_destroy,
            :id
          ]
        )
    end
end

app/views/pictures/_form.html.erb
<%= react_component('PictureForm', render(partial: 'pictures/picture_data.json.jbuilder',
                                          locals: { picture: @picture, form_type: form_type },
                                          format: :json))
%>

app/views/pictures/_picture_interest_fields.html.erb
<%# @deprecated %>
<div class="row col-sm-offset-2 form-group nested-fields">
  <%= interest_form.label :interest_id, 'Interest', class: 'col-sm-2 control-label' %>
  <div class="col-sm-4">
    <%= interest_form.select(:interest_id, options_for_select(@interests, interest_form.object.interest_id),{},{class: 'form-control'}) %>
  </div>
  <div class="col-sm-2">
    <%= interest_form.number_field :earned_points, placeholder: 'Weight', in: 1..5, step: 1, class: 'form-control' %>
  </div>
  <div class="col-sm-4">
    <%= link_to_remove_association 'Remove interest', interest_form, class: 'btn btn-warning' %>
  </div>
</div>

app/views/pictures/_picture_row.html.erb
<tr class="picture">
  <td class="col-sm-4">
    <% if picture.image.attachment.present? %>
      <%= image_tag url_for(picture.small_variant) %>
    <% end %>
  </td>
  <td class="col-sm-3">
    <h4>
      <%= picture.description %>
      <% if picture.audio.attachment.present? %>
                <span class="glyphicon glyphicon-volume-up"
                      aria-hidden="true"
                      title="<%= tf('entities.pictures.has_audio_description') %>"
                ></span>
      <% end %>
    </h4>
  </td>
  <td class="col-sm-3">
    <h4>
      <%= picture.related_interests.keys.join(', ') %>
    </h4>
  </td>
  <td class="col-sm-1">
    <%= link_to(tf('common.forms.edit'), edit_picture_path(picture.id), class: 'btn btn-warning') %>
  </td>
  <td class="col-sm-1">
    <%= link_to tf('common.forms.delete'),
                picture_path(picture.id),
                method: :delete,
                data: {
                    confirm: tf('entities.pictures.delete_confirm')
                },
                class: 'btn btn-danger'
    %>
  </td>
</tr>

app/views/pictures/edit.html.erb
<% provide(:title, tf('entities.pictures.update')) %>
<h1 class="row col-sm-offset-4"><%= tf('entities.pictures.update') %></h1>
<%= render 'pictures/form', form_type: 'edit' %>

app/views/pictures/index.html.erb
<%= javascript_include_tag 'picture_index' %>

<% provide(:title, tf('entities.pictures.all_pictures')) %>

<h1><%= tf('entities.pictures.all_pictures') %></h1>

<div class="row">
  <%= search_form_for @q do |f|%>
    <div class="form-group col-sm-4">
      <%= f.label :description_cont, tf('common.forms.search'), class: 'sr-only' %>
      <%= f.search_field :description_cont, {
          placeholder: tf('entities.pictures.search_prompt'),
          class: 'form-control'
      } %>
    </div>
    <%= f.submit tf('common.forms.search'), class: 'btn btn-primary col-sm-1' %>
  <% end %>
</div>

<div class="row">
  <%= link_to(tf('entities.pictures.create'), new_picture_path, class: 'btn btn-primary') %>
</div>

<div class="col-sm-12">
  <table id="pictures-list"
         class="table table-hover"
  >
    <thead>
    <tr>
      <td><%= tf('entities.pictures.fields.image') %></td>
      <td><%= tf('entities.pictures.fields.description') %></td>
      <td><%= tf('entities.pictures.related_interests') %></td>
      <td><%= tf('common.forms.edit') %></td>
      <td><%= tf('common.forms.delete') %></td>
    </tr>
    </thead>
    <tbody id="pictures-page">
      <%= render collection: @pictures, partial: 'pictures/picture_row', as: :picture %>
    </tbody>
  </table>
</div>

app/views/pictures/index.js.erb
<%= render(collection: @pictures, partial: 'pictures/picture_row', as: :picture) %>

app/views/pictures/new.html.erb
<% provide(:title, tf('entities.pictures.create')) %>
<h1 class="row col-sm-offset-4"><%= tf('entities.pictures.create') %></h1>
<%= render 'pictures/form', form_type: 'new' %>