config/routes.rb
Rails.application.routes.draw do

  # Login pages
  devise_for :users

  #Concerns
  concern :group_result do
    resources :result_of_tests, only: [:index], path: 'results', param: :result_id
  end

  #Routes
  root 'static_pages#home'

  #Static pages
  # get 'about' => 'static_pages#about'
  # get 'contacts' => 'static_pages#contacts'
  get 'home' => 'static_pages#home'

  #Interests pages
  resources :interests, only: [:index, :destroy]
  resources :interests, only: [] do
    collection do
      #Adding create and update routes to index page
      post '' => 'interests#create'
      patch '' => 'interests#update'
    end
  end

  #User pages...
  #...Administrators
  resources :administrators, concerns: :group_result  do
    member do
      get 'delete' => 'administrators#delegate'
      delete 'delete' => 'administrators#delete'
    end
  end

  #...Mentors
  resources :mentors, concerns: :group_result do
    member do
      get 'delete' => 'mentors#delegate'
      delete 'delete' => 'mentors#delete'
    end
  end

  #...Clients
  resources :clients, concerns: :group_result do
    member do
      #Adding testing pages
      get 'tests' => 'testing_process#index', as: 'tests'
      get 'edit/update_mentors' => 'clients#update_mentors'
      get 'mode_settings' => 'clients#mode_settings'
      patch 'mode_settings' => 'clients#update_mode_settings'
    end
    resources :result_of_tests, except: [:new, :create, :index], path: 'results', param: :result_id
    get 'results/:result_id/heatmap'=> 'result_of_tests#show_heatmap', as: 'heatmap'
    get 'update_mentors' => 'clients#update_mentors', on: :new
  end

  scope '/testing_process' do
    get ':result_of_test_id/testing' => 'testing_process#testing', as: 'testing'
    post ':result_of_test_id/answer' => 'testing_process#answer', as: 'testing_answer'
    post 'clients/:id/tests/:test_id/start' => 'testing_process#begin', as: 'testing_begin'
    get ':result_of_test_id/finish' => 'testing_process#finish', as: 'finish_page'
  end

  #Tests pages
  resources :tests do
    get 'update_image' => 'tests#update_image', on: :new
    get 'questions/:question_number/get_image' => 'pictures#show'
    member do
      get 'summary_result', to: 'result_of_tests#summary_result'
      get 'edit/update_image' => 'tests#update_image'
    end
  end

  #Picture pages
  resources :pictures, except: [:show]

  # Translations
  resources :translations, only: %i[index update create] do
    collection do
      post :translated_columns, to: 'translations#create_translated_columns'
      patch 'translated_columns/:id', to: 'translations#update_translated_columns'
      post :create_language, to: 'translations#create_language'
    end
  end

  # Test availability
  resources :test_availabilities, only: %i[index] do
    collection do
      patch :batch_update, to: 'test_availabilities#batch_update'
    end
  end

  get 'summary_results', to: 'result_of_tests#summary_results'
  get 'summary_result_table', to: 'result_of_tests#summary_result_table'
end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id                   :integer          not null, primary key
#  is_super             :boolean
#  organisation         :string
#  info_id              :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  organisation_address :string
#

# @deprecated
class Administrator < ActiveRecord::Base
  include Userable

  before_validation :setup_fields, on: :create
  
  has_many :mentors, dependent: :restrict_with_error
  has_one :user, as: :userable
  # @deprecated
  belongs_to :info, inverse_of: :administrator, autosave: true, dependent: :destroy, optional: true
  
  validates :organisation, presence: true, length: { in: 5..30}
  validates :info_id, uniqueness: true
  validates :is_super, uniqueness: true, if: ->{ is_super }
  validates :is_super, exclusion: { in: [nil] }
  validates :organisation_address, presence: true, uniqueness: true, length: { in: 5..100}

  # validates_presence_of :info
  # validates_associated :info, allow_blank: true

  accepts_nested_attributes_for :info
  accepts_nested_attributes_for :mentors

  def username
    "#{info.name} #{info.last_name} | Administrator"
  end

  #returns list of admins for viewing
  def self.admins_list
    Administrator.where(is_super: false).order(:organisation).map {
      |t| ['%{org}: %{lname} %{name}'%{org: t.organisation, lname: t.info.last_name, name: t.info.name},t.id]
      }
  end

  #Setups default fields
  def setup_fields
    self.is_super = false
    true
  end

  #Full information about admin
  def show
    user_info = self.info.show
    user_info[:organisation] = self.organisation
    user_info[:organisation_address] = self.organisation_address
    user_info
  end

  #Short information about admin
  def show_short
    user_info = self.info.show_short
    user_info[:organisation] = self.organisation
    user_info[:organisation_address] = self.organisation_address
    user_info[:id] = self.id
    user_info
  end

  #Returns other administrators for viewing in option-html-tag
  def other_administrators
    Administrator.where.not(['id = ? or is_super = ?',self.id, true]).order(:organisation).map {
        |t| ['%{org}: %{lname} %{name}'%{org: t.organisation, lname: t.info.last_name, name: t.info.name},t.id]
    }
  end

  def self.all_administrators
    select(
        'a.name as name, a.last_name as last_name, administrators.id as id,
        organisation, organisation_address'
    ).joins('JOIN infos as a on administrators.info_id = a.id').where(is_super: false)
  end
  ransack_alias :full_name, :info_last_name_or_info_name
end

app/controllers/administrators_controller.rb
class AdministratorsController < AdminController
  translations_for_preload %i[
    common.flash.account_created
    common.flash.administrator_cant_be_deleted
    common.flash.administrator_deleted
    common.flash.no_access
    common.flash.update_complete
    common.forms.confirm
    common.forms.delete
    common.forms.edit
    common.kaminari.first
    common.kaminari.last
    common.kaminari.next
    common.kaminari.previous
    common.menu.all
    common.menu.create
    common.menu.log_out
    common.menu.my_profile
    common.menu.profile
    common.menu.settings
    entities.clients.create
    entities.clients.index
    entities.employees.fields.last_name
    entities.employees.fields.name
    entities.employees.fields.organisation
    entities.employees.fields.organisation_address
    entities.employees.fields.phone
    entities.employees.phone_prompt
    entities.interests.index
    entities.local_administrators.create
    entities.local_administrators.index
    entities.local_administrators.update
    entities.mentors.create
    entities.mentors.index
    entities.pictures.index
    entities.tests.index
    entities.users.fields.email
  ]

  before_action :preload_entity, only: %i[edit update show delete delegate]

  def new
    authorize!
    @user = User.new
    @user.build_employee
  end

  def create
    authorize!
    @user = User.new(administrator_params)
    @user.role = :local_admin
    @user.userable = @user.build_employee(administrator_params[:employee_attributes])
    @user.skip_confirmation! # FIXME: Mocked because email service is not working

    if @user.save
      flash[:success] = tf('common.flash.account_created')

      redirect_to administrator_path(@user)
    else
      render :new
    end
  end

  def index
    authorize!
    @q = User.all_local_admins.joins(:employee).ransack(params[:q])
    @admins = params[:q] && params[:q][:s] ? @q.result.order(params[:q][:s]) : @q.result
    @admins = @admins.page(params[:page]).per(5)
  end

  def edit
    authorize!(@user)
  end
  
  def update
    authorize!(@user)

    if @user.update(administrator_params)
      flash[:success] = tf('common.flash.update_complete')
      redirect_to administrator_path(@user)
    else
      render :edit
    end
  end

  def show
    authorize!(@user)
    # TODO Make presenter
    @user_info = translate_hash(@user.show_nested)
  end

  def delegate
    authorize!(@user)
    @administrator = @user

    # TODO FIX BUG scope returns ALL other entities, but not related to old one
    # Loading information about mentors and admins for page
    @admins = User
      .includes(:employee)
      .other_local_admins(@administrator.id)
      .map(&:employee)
      .map do |t|
        ['%{org}: %{lname} %{name}' % { org: t.organisation, lname: t.last_name, name: t.name }, t.id]
      end
  end

  def delete
    authorize!(@user)
    @administrator = @user

    employee = @administrator.employee
    # Admin can be deleted only if hasn't mentors
    if employee.employees.empty? || employee.update(delete_administrator_params)
      if @administrator.reload.destroy
        flash[:success] = tf('common.flash.administrator_deleted')
        redirect_to administrators_path and return
      end
    end

    @admins = User
      .includes(:employee)
      .other_local_admins(@administrator.id)
      .map(&:employee)
      .map do |t|
        ['%{org}: %{lname} %{name}' % { org: t.organisation, lname: t.last_name, name: t.name }, t.id]
      end
    render :delegate
  end

  private

    def preload_entity
      @user = User.find_by(id: params[:id])
    end

    # @deprecated
    def load_admin_for_deletion
      administrator = User.find(params[:id])
      #Blocking a deletion of super administrator
      if administrator.super_admin?
        flash[:danger] = tf('common.flash.administrator_cant_be_deleted')
        redirect_to show_path_resolver(current_user)
      end
      administrator
    end

    def administrator_params
      params
        .require(:user)
        .permit(
          :email,
          :password,
          :password_confirmation,
          :language_id,
          employee_attributes: %i[id organisation phone organisation_address last_name name]
        )
        .tap do |p|
          p.delete(:password) if p[:password].blank?
          p.delete(:password_confirmation) if p[:password_confirmation].blank?
        end
    end

    #Attributes for delete forms
    def delete_administrator_params
      params.require(:employee).permit(employees_attributes: %i[employee_id id])
    end

    #Callback for checking rights
    # @deprecated
    def check_rights
      #Only SA or user can edit/delete their accounts
      unless is_super? || current_user.local_admin? && current_user.id == params[:id].to_i
        flash[:danger] = tf('common.flash.no_access')
        #Redirect
        redirect_to show_path_resolver(current_user)
      end
    end

    #Callback for checking type of user
    # @deprecated
    def check_type_rights
      unless current_user.local_admin? || is_super?
        flash[:danger] = tf('common.flash.no_access')
        redirect_to show_path_resolver(current_user)
      end
    end

    #Callback for checking existence of record
    # @deprecated
    def check_exist_callback
      unless check_exist(params[:id], User)
        redirect_to show_path_resolver(current_user)
      end
    end
end

app/views/administrators/_form.html.erb
<%= render 'shared/error_message' %>

<%= form_for @user,
             url: @user.new_record? ? administrators_path : administrator_path(@user),
             class: 'form-horizontal' do |f|
%>
  <%= f.fields_for :employee,
                   class: 'form-horizontal' do |ff|
  %>
    <%= render partial: 'employees/form',
               locals: {
                 f: ff
               }
    %>
  <% end %>

  <%= render partial: 'users/form',
             locals: {
               f: f
             }
  %>

  <div class="row col-sm-offset-2 form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit tf('common.forms.confirm'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/administrators/_settings.html.erb
<li>
  <%= link_to tf('entities.result_of_tests.summary_test_result'), summary_results_path %>
</li>
<% if is_super? %>
  <li>
    <%= link_to tf('entities.test_availabilities.index'), test_availabilities_path %>
  </li>
  <li>
    <%= link_to tf('entities.translations.index'), translations_path %>
  </li>
  <li>
    <%= link_to tf('entities.interests.index'), interests_path %>
  </li>
  <li>
    <%= link_to tf('entities.pictures.index'), pictures_path %>
  </li>
  <li>
    <%= link_to tf('entities.tests.index'), tests_path %>
  </li>
<% end %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= tf('common.menu.create') %> <b class="caret"></b>
  </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to tf('entities.clients.create'), new_client_path %>
      </li>
      <li>
        <%= link_to tf('entities.mentors.create'), new_mentor_path %>
      </li>
      <% if is_super? %>
        <li>
          <%= link_to tf('entities.local_administrators.create'), new_administrator_path %>
        </li>
      <% end %>
    </ul>
</li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= tf('common.menu.all') %> <b class="caret"></b>
</a>
	<ul class="dropdown-menu">
		<li>
			<%= link_to tf('entities.clients.index'), clients_path %>
		</li>
    <li>
      <%= link_to tf('entities.mentors.index'), mentors_path %>
    </li>
		<% if is_super? %>
		<li>
			<%= link_to tf('entities.local_administrators.index'), administrators_path %>
		</li>
		<% end %>
	</ul>
</li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= tf('common.menu.profile') %> <b class="caret"></b>
</a>
	<ul class="dropdown-menu">
		<li>
			<%= link_to tf('common.menu.settings'), edit_administrator_path(current_user) %>
		</li>
		<li>
			<%= link_to tf('common.menu.my_profile'), administrator_path(current_user) %>
		</li>
	</ul>
</li>
<li>
  <%= link_to tf('common.menu.log_out'), destroy_user_session_path, method: "delete" %>
</li>

app/views/administrators/delegate.html.erb
<% provide(:title, tf('entities.local_administrators.delete')) %>
<h1 class="row col-sm-offset-4"><%= tf('entities.local_administrators.delete') %></h1>
<h3 class="row col-sm-offset-2"><%= tf('entities.local_administrators.delegate_prompt') %></h3>
<%= render 'shared/error_message' %>

<%= form_for @administrator.employee,
             url: delete_administrator_path(@administrator.id),
             method: :delete,
             html: { class: 'form-horizontal' } do |f|
%>
  <%= f.fields_for :employees do |ff| %>

    <!-- Choosing new admin-->
    <div class="row col-sm-offset-2 form-group">
      <%= ff.label :employee_id,
                   tf('entities.local_administrators.delegate_prompt', options: { for: ff.object.last_name }),
                   class: 'col-sm-4 control-label'
      %>
      <div class="col-sm-4">
        <%= ff.select :employee_id,
                     options_for_select(@admins),
                     {},
                     { class: 'form-control' }
        %>
      </div>
    </div>
  <% end %>

  <div class="row col-sm-offset-2 form-group">
      <div class="col-sm-offset-2 col-sm-2">
        <%= f.submit tf('common.forms.delete'),
                      data: { confirm: tf('common.forms.delete_confirm') },
                      class: 'btn btn-danger'
        %>
      </div>
    </div>
<% end %>

app/views/administrators/edit.html.erb
<% provide(:title, 'Edit administrator') %>
<h1 class="row col-sm-offset-4"><%= tf('entities.local_administrators.update') %></h1>
<%= render partial: 'administrators/form' %>

app/views/administrators/index.html.erb
<% provide(:title, tf('entities.local_administrators.all_administrators')) %>
<h1 class="col-sm-12"><%= tf('entities.local_administrators.all_administrators') %></h1>
<div>
  <%= search_form_for @q, url: administrators_path do |f| %>
      <div class="form-group col-sm-4">
        <%= f.label :full_name_cont,
                    tf('common.forms.search'),
                    class: 'sr-only'
        %>
        <%= f.search_field :full_name_cont,
                           {
                             placeholder: tf('entities.local_administrators.search_prompt'),
                             class: 'form-control'
                           }
        %>
      </div>
      <%= f.submit tf('common.forms.search'), class: 'btn btn-primary col-sm-1' %>
  <% end %>
</div>
<div class="col-sm-12">
	<table class="table table-hover">
    <thead>
      <tr>
        <td><%= sort_link @q, 'employees.last_name', tf('entities.employees.fields.last_name') %></td>
        <td><%= sort_link @q, 'employees.name', tf('entities.employees.fields.name') %></td>
        <td><%= sort_link @q, 'employees.organisation', tf('entities.employees.fields.organisation') %></td>
        <td><%= sort_link @q, 'employees.organisation_address', tf('entities.employees.fields.organisation_address') %></td>
        <td><%= tf('common.menu.profile') %></td>
        <td><%= tf('common.forms.edit') %></td>
        <td><%= tf('common.forms.delete') %></td>
      </tr>
    </thead>
		<% @admins.each do |admin| %>
			<tr>
        <% employee = admin.employee %>
				<td><h4><%= employee[:last_name].titleize %></h4></td>
        <td><h4><%= employee[:name].titleize %></h4></td>
        <td><h4><small><%= employee[:organisation].titleize %></small></h4></td>
        <td><h4><small><%= employee[:organisation_address].titleize %></small></h4></td>
        <td><%= link_to(tf('common.menu.profile'), administrator_path(admin[:id]), class: 'btn btn-default') %></td>
				<td><%= link_to(tf('common.forms.edit'), edit_administrator_path(admin[:id]), class: 'btn btn-warning') %></td>
        <td><%= link_to(tf('common.forms.delete'), delete_administrator_path(admin[:id]), class: 'btn btn-danger') %></td>
			</tr>
		<% end %>
	</table>
</div>
<div class="col-sm-12">
  <%= paginate @admins %>
</div>

app/views/administrators/new.html.erb
<% provide(:title,'New administrator') %>
<h1 class="row col-sm-offset-4"><%= tf('entities.local_administrators.create') %></h1>
<%= render partial: 'administrators/form' %>

app/views/administrators/show.html.erb
<div class="row">
	<%= render "shared/profile" %>
</div>
<% if is_super? and current_user.role_model.id != params[:id].to_i %>
	<div class="row">
		<div class="btn-group col-sm-4" role="group" aria-label="...">
			<%= link_to(tf('common.forms.edit'), edit_administrator_path(params[:id]), class: "btn btn-warning") %>
			<%= link_to(tf('common.forms.delete'), delete_administrator_path(params[:id]), class: 'btn btn-danger') %>

		</div>
	</div>
<% end %>